# Tomcat Server

server:
  port: 8080

# Logger

logging.level:
  com.busyqa.course: DEBUG
  org.hibernate.type: INFO

# Active Profile
 
spring:
  profiles:
    active: prod
    
# Banner Text

  banner:
    charset: UTF-8
    location: classpath:/banner/busyQA.txt

# Jackson Settings

  jackson:
    date-format: "dd-MM-yyyy"
        
---

# Default Profile

spring:
  profiles: default

# Database Settings
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
    continue-on-error: false
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        
---
        
# Prod Profile

spring:
  profiles: prod
  
# Database Settings 
  datasource:
    url: jdbc:mysql://busyqa-rds.javadev.ca:3306/usersdb?autoReconnect=true&useSSL=false&useUnicode=true&serverTimezone=UTC  
    username: busyqa
    password: busyqa123$
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-wait: 10000
      max-active: 15
      max-idle: 10
      initial-size: 3
      test-on-borrow: true
    continue-on-error: false
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        use-new-id-generator-mappings: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  
           